### ISSUE TITLE
无法用pm2进行管理

### ISSUE THREAD

**Issue by latermonk** [ogilhinn/koa2-wechat#2]
Hi 运行你的这个后台程序发现一个问题， 只能用node app.js & 放到后台运行，如果是用 sudo pm2 start app.js  --name "wechat" ,一放后台就报错，error.[用 sudo pm2 list 查看] 。

**Comment by liuxing** [comment]
pm2 logs看下

**Comment by latermonk** [comment]
明白 是因为pm2总是去使用系统上的一个 6.x版本的node ，而我指定的8.9.4的node却没有生效。直接打node -v 显示 v8.9.4.不止为啥。

**Comment by latermonk** [comment]
不知道是哪里的原因，暂时用 sudo pm2  start app.js --name "iChat"  --interpreter "/home/abc/git/nvm/versions/node/v8.9.4/bin/node"  解决了，难道是nvm的问题？
