### ISSUE TITLE
lesson3  运行报错  errcode: 40001

### ISSUE THREAD

**Issue by latermonk** [ogilhinn/koa2-wechat#3]
报错：

errcode: 40001,
  errmsg: 'invalid credential, access_token is invalid or not latest hint:

[全局返回码](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433747234)
这个怎么调试 ？

备注：
1.使用微信官方的的调试工具 调试是可以正常获取到 access_token的 
[微信接口调试工具](https://mp.weixin.qq.com/debug/cgi-bin/apiinfo?t=index&type=%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95&form=%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95%E5%88%9B%E5%BB%BA%E6%8E%A5%E5%8F%A3%20/menu/creat)

2.不管是订阅号还是公众测试号都不行

3.node是 8.9.4  axios & fs-extra 也都安装过了

谢谢！

**Comment by liuxing** [comment]
看看你测试号的配置是不是对的，access_token.txt中写入了什么内容

未认证个人订阅号没有自定义菜单的权限

**Comment by latermonk** [comment]
1.测试好配置是写在 config.js
module.exports = {
    wechat:{
        appID:'xxx', //填写你自己的appID
        appSecret:'xxx',  //填写你自己的appSecret
        token:'xxx'  //填写你自己的token
    }
};


2.cat  access_token.txt:
{"expireTime":null}%

感觉这个文件有问题，一是没有access_token,二是没获取到7200

怎么破？

**Comment by liuxing** [comment]
appid, appsecret小写
